# -*- coding: utf-8 -*-
"""sentence embeddings pretrained model

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJla54kFDWRjVrp1_hR08GbrxYPVNqNW

References:
https://github.com/UKPLab/sentence-transformers

https://www.sbert.net/docs/pretrained_models.html

https://stats.stackexchange.com/questions/318882/what-does-average-of-word2vec-vector-mean
"""

from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

import pandas, numpy, csv, string
import pandas as pd
#https://colab.research.google.com/github/gal-a/blog/blob/master/docs/notebooks/nlp/nltk_preprocess.ipynb#scrollTo=-44aMwUcQZxm
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
import unicodedata
import re

!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown fox jumps over the lazy dog.']
sentence_embeddings = model.encode(sentences)

for sentence, embedding in zip(sentences, sentence_embeddings):
    print(len(embedding))
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

headline_data = pandas.read_excel('/content/drive/MyDrive/Headline Only - Without Duplicates.xlsx')
headline_list=list(headline_data['headline'])
headline_embeddings = model.encode(headline_list)
headline_list
# for headline, embedding in zip(headline_list, headline_embeddings):
#     print(len(embedding))
#     print("Sentence:", headline)
#     print("Embedding:", embedding)
#     print("")

"""Find length of an array for each row. Change the number in the square brackets to any row number to ensure that the length of array is the same for each"""

len(headline_embeddings[10000]) #384 embeddings for each row

"""Convert embeddings array to dataframe"""

headline_embeddings_df = pd.DataFrame(headline_embeddings)

headline_embeddings_df

"""Save dataframe to excel"""

headline_embeddings_df.to_excel('/content/drive/My Drive/headline_embeddings.xlsx')